In [39]:
# code to sort a list in python without using sort()
my_list = [4, 2, 3, 0, 1]

for i in range(len(my_list)):
    print("1:",my_list[i])
    for j in range(i + 1, len(my_list)):
        print("2:",my_list[j])
        if my_list[i] > my_list[j]:
            my_list[i], my_list[j] = my_list[j], my_list[i]
        print(my_list)

print(my_list)

1: 4
2: 2
[2, 4, 3, 0, 1]
2: 3
[2, 4, 3, 0, 1]
2: 0
[0, 4, 3, 2, 1]
2: 1
[0, 4, 3, 2, 1]
1: 4
2: 3
[0, 3, 4, 2, 1]
2: 2
[0, 2, 4, 3, 1]
2: 1
[0, 1, 4, 3, 2]
1: 4
2: 3
[0, 1, 3, 4, 2]
2: 2
[0, 1, 2, 4, 3]
1: 4
2: 3
[0, 1, 2, 3, 4]
1: 4
[0, 1, 2, 3, 4]


In [ ]:
# code to find the unique values in the list
a = [1, 2, 2, 3]
b = []
for i in a:
    if i not in b:
        b.append(i)
print (b)

[1, 2, 3]


In [41]:
# code to make fibonacci numbers using generators
def fib():
  a,b=0,1
  #infinite loop
  while True:
    yield a
    a,b=b,a+b

for f in fib():
  if f >50:
    break
  print(f)


# next(fib())   

0
1
1
2
3
5
8
13
21
34


In [27]:
for f in fib():
  if f >100:
    break
  print(f)

0
1
1
2
3
5
8
13
21
34
55
89


In [17]:
# code to make fibonacci numbers without generators
def fibonacci(n):
    a = 0
    b = 1
     
    # Check is n is less
    # than 0
    if n < 0:
        print("Incorrect input")
         
    # Check is n is equal
    # to 0
    elif n == 0:
        return a
       
    # Check if n is equal to 1
    elif n == 1:
        return b
    else:
        for i in range(1, n):
          print("1:",a,b)
          a,b=b,a+b
          print("2:",a,b)
          print("3:",b)
        return b
print(fibonacci(9))

1: 0 1
2: 1 1
3: 1
1: 1 1
2: 1 2
3: 2
1: 1 2
2: 2 3
3: 3
1: 2 3
2: 3 5
3: 5
1: 3 5
2: 5 8
3: 8
1: 5 8
2: 8 13
3: 13
1: 8 13
2: 13 21
3: 21
1: 13 21
2: 21 34
3: 34
34


In [31]:
# inheritance
class Vehicle:
  def general_usage(self):
    print("general use: transportation")

# to perform inheritance we put vehicle class inside car class

class Car(Vehicle):
  def __init__(self):
    print("I'm car")
    self.wheels=4
    self.has_roof=True

  def specific_usage(self):
    #during revision comment this below line
    self.general_usage()
    print("specific use: commute to work, vacation with family")

class Bike(Vehicle):
    def __init__(self):
      print("I'm bike")
      self.wheels=2
      self.has_roof=False

    def specific_usage(self):
      #here we inherit specific_usage function from vehicle class
      #during revision comment this below line
      self.general_usage()
      print("specific use: racing, masti")

# let's create objects
c=Car()
# we inherit general_usage function from Vehicle class
# c.general_usage()
c.specific_usage()

I'm car
general use: transportation
specific use: commute to work, vacation with family


In [9]:
#multiple inheritance
class Father():
  def gardening(self):
    print('I enjoy gardening')

class Mother():
  def cooking(self):
    print("I love cooking")

class Child(Father,Mother):
  def sports(self):
    print("I enjoy sports")

c=Child()
c.gardening()
c.cooking()
c.sports()

# if all the classes have same method
class Father():
  def enjoy(self):
    print('I enjoy gardening')

class Mother():
  def enjoy(self):
    print("I love cooking")

class Child(Father,Mother):
  def enjoy(self):
    # if all the mehtods have same then we have to call these methods here in child class
    Father.enjoy(self)
    Mother.enjoy(self)
    print("I enjoy sports")

d=Child()
d.enjoy()

I enjoy gardening
I love cooking
I enjoy sports
I enjoy gardening
I love cooking
I enjoy sports


In [14]:
# Multithreading
# there is a time when we are calling a web server or waiting for packet in our network socket and our cpu is not doing anything multi-threading tries to utilize this idle time
import time

def calc_square(numbers):
  print("calculate square numbers")
  for n in numbers:
    # it is for suspending the execution of our current function for some time
    time.sleep(0.2)
    print('square:',n*n)

def calc_cube(numbers):
  print("calculate cube of numbers")
  for n in numbers:
    time.sleep(0.2)
    print('cube:',n*n*n)

arr=[2,3,8,9]
t=time.time()
calc_square(arr)
calc_cube(arr)

print("done in : ",time.time()-t)
print("Hah... I am done with all my work now!")

# now we will apply multi-threading
import threading

def calc_square(numbers):
  print("calculate square numbers")
  for n in numbers:
    time.sleep(0.2)
    print('square:',n*n)

def calc_cube(numbers):
  print("calculate cube of numbers")
  for n in numbers:
    time.sleep(0.2)
    print('cube:',n*n*n)

arr=[2,3,8,9]
t=time.time()

t1=threading.Thread(target=calc_square, args=(arr,))
t2=threading.Thread(target=calc_cube,args=(arr,))
# starting the thread
t1.start()
t2.start()
# joining the thread to main program
t1.join()
t2.join()

print("done in : ",time.time()-t)
print("Hah... muti-threading is taking less time as compared to normal way")


calculate square numbers
square: 4
square: 9
square: 64
square: 81
calculate cube of numbers
cube: 8
cube: 27
cube: 512
cube: 729
done in :  1.60756516456604
Hah... I am done with all my work now!
calculate square numbers
calculate cube of numbers
square: 4
cube: 8
square: 9
cube: 27
square: 64
cube: 512
square: 81
cube: 729
done in :  0.8070244789123535
Hah... muti-threading is taking less time as compared to normal way


In [ ]:
# multiprocessing vs multithreading
# Both are ways to achieve multitasking (when we are trying to work on multi-task at the same time)
# Thread will have their own stack memory own instruction pointer only they share is their address space which means if we have global variable in our programs they can be shared by multiple threads
# and heap memory can be accessed by this
# The benefit of multiprocessing is that error or memory leak in one process won't hurt execution of another process
# on the other if thread faces error or memory it can hurt all other threads

In [20]:
# Multiprocessing
from multiprocessing import Pool
import time

def f(n):
  sum=0
  for x in range(10000):
    sum+=x*x
  return sum

t1=time.time()
p=Pool()
result=p.map(f,range(10000))
p.close()
p.join()

print("Pool took:",time.time()-t1)

t2=time.time()
result=[]
for x in range(10000):
  result.append(f(x))
print("Serial processing took: ",time.time()-t2)




Pool took: 11.255397319793701
Serial processing took:  10.7020263671875


In [32]:
# List set dict comprehensions
numbers=[1,2,3,4,5,6,7]
# using traditinal method
even=[]
for i in numbers:
  if i%2==0:
    even.append(i)
print(even)
# List comprehensions will provide the way to get our code done in 1 line
even=[i for i in numbers if i%2==0]
print('List comp way', even)
sqr_number=[i*i for i in numbers]
print(sqr_number)
# set comprehensions
# traditional way
s=set([1,2,3,4,5,2,3])
print(s)
# set comprehensions
even={i for i in s if i%2==0}
print(even)
# Dictionary compreshions
cities=["jammu","new york","paris"]
countries=["india","usa","france"]
# zip is a inbuild function in python which zip two list together
z=zip(cities,countries)
# z is object of zip class 
# enumerate is class for counting the iterations
for a in enumerate(z):
  print(a)
d={city:country for city,country in zip(cities,countries)}
print(d)

[2, 4, 6]
List comp way [2, 4, 6]
[1, 4, 9, 16, 25, 36, 49]
{1, 2, 3, 4, 5}
{2, 4}
(0, ('jammu', 'india'))
(1, ('new york', 'usa'))
(2, ('paris', 'france'))
{'jammu': 'india', 'new york': 'usa', 'paris': 'france'}


In [13]:
import numpy as np
import time
import sys
a=np.array([1,2,3])
print(a)
# it is similar to list why we need numpy?
print(a[1])
print(a[2])
# it has 3 benefits: 1) it takes less memory, 2) it is fast, 3) it is convinient
# in python everything is a object so each element in list will store 14 bytes where as numpy array 1 element will store 4 bytes
l=range(1000)
print("list memory of elements in list is ",sys.getsizeof(1)*len(l))
array=np.arange(1000)
print("list memeory of all the elements in array is ",array.size*array.itemsize)
# np.array is fast
size=1000000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start))
# numpy array
start=time.time()
result=a1+a2
print("numpy took: ", (time.time()-start))
# convinient
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)

[1 2 3]
2
3
list memory of elements in list is  28000
list memeory of all the elements in array is  8000
python list took:  0.11591005325317383
numpy took:  0.020134449005126953
[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# pandas has default of int64 but if we have data which is between 1 to 11 then we can convert it into dtype{"column_name":"int8"}
# to use only 2 columns when loading csv file using pandas we can write df=pd.read_csv('example.csv',usecols=["First Name","Last Name"]) it will take less memory
# for pandas refer https://www.youtube.com/watch?v=HNE0qHJ9A9o
# for memory saving tricks refer https://pythonspeed.com/articles/pandas-load-less-data/